package io.mosip.packet.core.constant;

public enum DatabaseQueries {
    MYSQL_TABLE_LIST("SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '%s' ORDER BY TABLE_NAME"),
    ORACLE_TABLE_LIST("SELECT OWNER AS SCHEMA_NAME, TABLE_NAME AS TABLE_NAME FROM ALL_TABLES WHERE OWNER = '%s' ORDER BY TABLE_NAME"),
    MSSQL_TABLE_LIST("SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES T ORDER BY TABLE_NAME"),
    POSTGRESQL_TABLE_LIST("SELECT TABLE_SCHEMA, TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='%s' ORDER BY TABLE_NAME"),
    ORACLE_COLUMN_LIST("SELECT '' AS TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH  AS LENGTH FROM USER_TAB_COLUMNS WHERE TABLE_NAME = '%s' ORDER BY COLUMN_NAME"),
    MYSQL_COLUMN_LIST("SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, IFNULL(CHARACTER_MAXIMUM_LENGTH, CONCAT(NUMERIC_PRECISION, ',', NUMERIC_SCALE)) AS LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='%s' ORDER BY COLUMN_NAME"),
    MSSQL_COLUMN_LIST("SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, ISNULL(CAST(CHARACTER_MAXIMUM_LENGTH AS varchar), CONCAT(NUMERIC_PRECISION, ',', NUMERIC_SCALE)) AS LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '%s' ORDER BY COLUMN_NAME"),
    POSTGRESQL_COLUMN_LIST("SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, NULLIF(CAST(CHARACTER_MAXIMUM_LENGTH AS varchar), CONCAT(NUMERIC_PRECISION, ',', NUMERIC_SCALE)) AS LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '%s' ORDER BY COLUMN_NAME");

    DatabaseQueries(String query) {
        this.query = query;
    }
    private final String query;

    public String getQuery() {
        return query;
    }
}
